name: EZN_RankUP
main: pt.elevenzeronine.rankup.RankupPlugin
version: 1.1
depend: [Vault]
softdepend: [MVdWPlaceholderAPI]
commands:
  rankup:
    description: rankup
  ranks:
    description: ranks
  givepickaxe:
    description: pickaxes
    permission: pickaxes.use
